name: Calcul SST Quotidien

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch: 

jobs:
  run-sst:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les bibliothèques
        run: pip install numpy pandas xarray netcdf4 gspread google-auth

      - name: Exécuter le script Python
        env:
          # On transmet la clé JSON masquée au script Python
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
        run: python script.py
